[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
ksupport = { path = "../libs/ksupport" }
log = { version = "0.4.20", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader_api = "0.11.4"
bootloader-x86_64-common = "0.11.4"
